### PR TITLE
PEP-8 Reformat

### PR DESCRIPTION
**Pull request by Travis42**
Can you appreciate the irony of a program designed to provide AFIs getting cited for a PEP 8 'violation'? :)

I wanted to read your code, and while doing so, thought it would be better if formatted according to PEP 8.  So here you go:

### CODE REVIEW

**Comment by HadManySons** [comment]
Yeah, I cut my teeth in C++, so the idea of using spaces instead of tabs almost makes me sick. I'll admit that I haven't looked into PEP-8 very much. Let me do some testing on it and then I'll probably pull it in.

Question though, there two commits here, which one is correct?

**Comment by Travis42** [comment]
The most recent one.  I think its saying there are conflicts because the pull request before mine that you recently merged changes around a few lines of code.

I'm a bit new to github collaboration.

**Comment by HadManySons** [comment]
Yeah, I figured it would create a conflict, but that's okay, its an opportunity to learn about conflict resolution now. I am also new to GitHub collab. I'll let you know when I get a chance to review it all and test it. I'm sure it works fine, but I want triple check everything before I merge it in.

**Comment by HadManySons** [comment]
Also, is that a flight suit and a morale shirt I see in your profile pic? What do you do? PM me on reddit if you don't want to answer here: /u/hadmanysons

**Comment by Travis42** [comment]
Will do

**Comment by Travis42** [comment]
EWO, RC-135.  You?

**Comment by Travis42** [comment]
Yep...must have been a Friday when that photo was taken. :)

**Comment by HadManySons** [comment]
C-130H FE

**Comment by HadManySons** [comment]
Everything appears to functions the same, merging.

**Comment by HadManySons** [comment]
Had to commit it again, apparently a colon got dropped from an else statement even though I tested the code. I only noticed after I committed this pull request and then cloned the code and ran it. Weird, since it ran fine if I copy-pasted the code out of the browser.

**Pull request merged**
